
# Win32 MSVC makefile.  Tested on MSYS/MinGW

# Need to have GLUT dll in system path + GLUT lib and headers properly
# installed under MSVC's installation dirs.  See GLUT documentation
# for more details.

all:
	cl -W4 -Feglut_sample.exe main.c
